import json
from typing import List
import pytest
from dotenv import load_dotenv

from socless_repo_parser.models import IntegrationFamily, SoclessFunction


@pytest.fixture(scope="session", autouse=True)
def load_dotenv_if_exists():
    load_dotenv()


def get_mock_file(file_name: str) -> str:
    MOCK_DIR_PATH = "tests/mock_files/"

    file_path = f"{MOCK_DIR_PATH}{file_name}"
    with open(file_path) as f:
        python_file_as_string = f.read()
    return python_file_as_string


def pytest_addoption(parser):
    # `tox -- --github`
    parser.addoption(
        "--github",
        action="store_true",
        default=False,
        help="run slow tests that touch github.com",
    )


def pytest_configure(config):
    # `tox -- --github`
    config.addinivalue_line("markers", "github: marks tests that touch github.com")


def pytest_collection_modifyitems(config, items):
    if config.getoption("--github"):
        # `tox -- --github`
        # --github given in cli: do not skip slow tests
        return
    skip_github = pytest.mark.skip(reason="need --github option to run")
    for item in items:
        if "github" in item.keywords:
            item.add_marker(skip_github)


@pytest.fixture(scope="session")
def mock_socless_info_output_as_dict() -> dict:
    # output generated by running `python3 main.py "twiio-labs/socless, twilio-labs/socless-slack" --org-name="twilio-labs"` on 9/10/2021
    with open("tests/mock_files/mock_output.json") as f:
        mock_output = json.loads(f.read())
    return mock_output


@pytest.fixture(scope="session")
def cached_socless_info_output_as_dict() -> dict:
    # output generated by running `python3 main.py "twiio-labs/socless, twilio-labs/socless-slack" --org-name="twilio-labs"` on 9/10/2021
    with open("socless_info.json") as f:
        mock_output = json.loads(f.read())
    return mock_output


def find_integration(
    integration_family_name: str, integrations: List[IntegrationFamily]
) -> IntegrationFamily:
    for integration in integrations:
        if integration.meta.integration_family == integration_family_name:
            return integration

    raise Exception(f"Integration not found: {integration_family_name}")


def find_function(function_deployed_name: str, functions: List[SoclessFunction]):
    for fn in functions:
        if fn.meta.deployed_lambda_name == function_deployed_name:
            return fn
    raise Exception(f"SoclessFunction not found: {function_deployed_name}")
